version: '3'

services:
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: your_access_key
      MINIO_SECRET_KEY: your_secret_key
    volumes:
      - ./data:/data
    command: server /data
